apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: vss-0-1-0
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      volumes:
      - name: search
        hostPath:
          path: /mnt/data/bangpc/nfs_storage/vss/vss-search
      containers:
        - name: search
          ports:
          - containerPort: 6000
            name: http
          image: "thienpn/vss-search:22.12-search-0.1"
          env:
            - name: DB_HOST
              value: "192.168.0.171:27017"
            - name: DB_NAME
              value: "vss-0-1-0"
            - name: S3_ENDPOINT_URL
              value: "192.168.0.171:9000"
            - name: SEARCH_PORT
              value: "6000"
          volumeMounts:
          - mountPath: /vss-search
            name: search
              #command: ["/bin/sh", "-c"]
            #args: ["cd /vss-search/vss_search/app && python3 main.py"]

---

apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: vss-0-1-0
  labels:
    app: search
spec:
  selector:
    app: search
  ports:
    - protocol: TCP
      port: 6000
      name: http
      targetPort: 6000
      nodePort: 32003
  type: NodePort
  # loadBalancerIP: 192.168.0.101
