apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deepstream
  namespace: vss-0-1-0
spec:
  serviceName: deepstream # the name of service
  selector:
    matchLabels:
      app: deepstream
  replicas: 1
  template: # pod template
    metadata:
      labels:
        app: deepstream
    spec:
      containers:
      - name: deepstream
        image: tienluongngoc/deepstream:6.1-triton-new-1.5.2-10g-deployment
        command: [ "sh", "-c"]
        args: ["python /home/VSS/scripts/save_env.py && /home/VSS/scripts/auto_start.sh"]
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_SERVICE_NAME
            value: deepstream
          - name: SERVICE_PORT
            value: "9089"
          - name: DB_HOST
            value: "192.168.0.171"
          - name: DB_PORT
            value: "27017"
          - name: DB_USER_NAME
            value: "mongouser"
          - name: DB_PASSWORD
            value: "123456aA@"
          - name: DB_DATABASE_NAME
            value: "vss-0-1-0"
        ports:
          - name: http
            containerPort: 9089
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: deepstream
  namespace: vss-0-1-0
spec:
  clusterIP: None
  selector:
    app: deepstream
  ports:
    - name: http
      port: 9089
